apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: next-rewards-

commonLabels:
  bot: next-rewards

patchesStrategicMerge:
  - deployment_set_bot.yaml
