apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  template:
    spec:
      containers:
      - name: bot
        args: ["src.cco2_price.main"]
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bots-secret
              key: DISCORD_BOT_TOKEN_CCO2_PRICE
