apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: dao-balance-

commonLabels:
  bot: dao-balance

patchesStrategicMerge:
  - deployment_set_bot.yaml
